### ISSUE TITLE
module 'oauth2client' has no attribute 'file'

### ISSUE THREAD

**Issue by tigofat** [tokland/youtube-upload#275] opened 2019-03-15 17:22 UTC
Even when I add 'from oauth2client import file' to main.py it does not stop giving be this error.
AttributeError: module 'oauth2client' has no attribute 'file'

**Comment by csmccc** [comment] 2019-03-25 08:25
from oauth2client import file

**Comment by rjbell4** [comment] 2019-03-30 07:38
Or `pip install google-api-python-client==1.7.4` (or `pip3`)

**Comment by alopezag** [comment] 2019-06-07 03:24
It works when adding the import into the file `youtube_upload/auth/__init__.py`

```python
from oauth2client import file
```

**Comment by ChillerDragon** [comment] 2019-12-26 12:55
Shouldn't that be documented in the readme or fixed in the code?

**Comment by Juaran** [comment] 2020-01-03 06:40
> Or `pip install google-api-python-client==1.7.4` (or `pip3`)

It works for me, tks!

**Comment by tthill** [comment] 2020-01-07 21:51
> Or `pip install google-api-python-client==1.7.4` (or `pip3`)

This worked for me too.

**Comment by kootsoop** [comment] 2020-05-06 15:13
Closing as duplicate of #245

**Closed by kootsoop** 2020-05-06 15:13 UTC
