### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by MelcomX** [tokland/youtube-upload#162] opened 2017-02-11 13:07 UTC
Hello

I'm having an error, when uploading an Video to youtube.:

`UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 1441: ordinal not in range(128)`

I had the same file uploaded to an other Youtube-channel, from the same machine, with no erros. The command I used is:
`youtube-upload --title="Title" 1.mp4`
I think it's a bug, but I can't say what it is...

**Comment by KenSharp** [comment] 2017-03-12 21:08
What is your operating system? UTF works fine for me on Linux.

**Comment by kootsoop** [comment] 2020-05-07 02:10
Seems like a duplicate of #216

**Closed by kootsoop** 2020-05-07 02:10 UTC
Labels: character set issue, duplicate
