### ISSUE TITLE
Error after entering the verification code

### ISSUE THREAD

**Issue by ratneshdeepak** [tokland/youtube-upload#115] opened 2016-06-19 08:10 UTC
**OverflowError: normalized days too large to fit in a C int**

Start upload: vid.mp4
  0% |                                                                                                                      | ETA:  --:--:--   0.0 s/BTraceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 251, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 39, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 246, in main
    run_main(parser, options, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 178, in run_main
    video_id = upload_youtube_video(youtube, options, video_path, len(args), index)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 142, in upload_youtube_video
    progress.finish()
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 83, in _finish
    return bar.finish()
  File "/usr/local/lib/python2.7/dist-packages/progressbar/bar.py", line 526, in finish
    self.update(self.max_value)
  File "/usr/local/lib/python2.7/dist-packages/progressbar/bar.py", line 475, in update
    StdRedirectMixin.update(self, value=value)
  File "/usr/local/lib/python2.7/dist-packages/progressbar/bar.py", line 110, in update
    DefaultFdMixin.update(self, value=value)
  File "/usr/local/lib/python2.7/dist-packages/progressbar/bar.py", line 42, in update
    self.fd.write('\r' + self._format_line())
  File "/usr/local/lib/python2.7/dist-packages/progressbar/bar.py", line 412, in _format_line
    widgets = ''.join(self._format_widgets())
  File "/usr/local/lib/python2.7/dist-packages/progressbar/bar.py", line 392, in _format_widgets
    widget_output = widget(self, data)
  File "/usr/local/lib/python2.7/dist-packages/progressbar/widgets.py", line 282, in __call__
    data['eta'] = utils.format_time(data['eta_seconds'])
  File "/usr/local/lib/python2.7/dist-packages/progressbar/utils.py", line 222, in format_time
    time = datetime.timedelta(seconds=int(time))
OverflowError: normalized days too large to fit in a C int

**Comment by ratneshdeepak** [comment] 2016-06-19 08:11
Environment : Ubuntu 64 bit 14.04 LTS

**Comment by ayush--s** [comment] 2016-06-19 23:17
duplicate of #116

**Comment by tristangrimaux** [comment] 2016-06-19 23:50
I've just seen it. Please change the title of your bug so it's easier to find!!!

**Comment by tokland** [comment] 2016-06-21 20:40
duplicate #116

**Closed by tokland** 2016-06-21 20:40 UTC
