### ISSUE TITLE
Is there a way to add line breaks to the description?

### ISSUE THREAD

**Issue by pfgp** [tokland/youtube-upload#272] opened 2019-02-16 16:38 UTC
I am trying to add line breaks to my video descriptions.

youtube-upload ... --description="Line 1\r\nLine2" video.mp4

The above example doesn't work, but is it possible?

**Comment by mrbesen** [comment] 2019-03-08 10:27
just ```\n``` works for me.

**Comment by televisedBow** [comment] 2019-03-08 17:56
I'm using this in a Ruby environment and pass a string with `\n` in it. The description renders with line breaks for me.

**Comment by mrbesen** [comment] 2019-03-08 22:22
when you have another program calling youtube_upload you might need to double escape the string with ```\\n``` and / or ```\"```

**Comment by ZainRizvi** [comment] 2019-04-22 07:35
Seems like this issue can be safely closed

**Comment by jangxx** [comment] 2019-04-30 10:25
I have a bash script where I'm trying to add newlines as well, but neither `desc="..\n.."` nor `desc="..\\n.."` worked for me when I put the variable in the description parameter (`--description="$desc"`). The literal \n was put in the description both times, so I would like to know how this is supposed to work as well.

**Comment by mrbesen** [comment] 2019-04-30 10:52
but --description="..\n.." works for you?

**Comment by jangxx** [comment] 2019-04-30 14:00
No it doesn't, neither with \n, nor with \\n. I just wanted to clarify that I use it in a script and with variables instead of manually typing in the shell. I'm not sure if there is any actual difference between the two, though.

**Comment by jangxx** [comment] 2019-05-03 10:50
For future reference: The workaround I found to be working makes use of process substitution:

```bash
desc="something\n\with\nnewlines"
youtube-upload --description-file=<(echo -e "$desc") ...
```

It's not ideal but works reliably and without dirty hacks.

**Comment by kootsoop** [comment] 2020-05-06 15:55
Closing as duplicate of #243

**Closed by kootsoop** 2020-05-06 15:55 UTC
