### ISSUE TITLE
AttributeError: module 'oauth2client' has no attribute 'file' - Main.py missing import?

### ISSUE THREAD

**Issue by dKatsuro** [tokland/youtube-upload#262] opened 2018-12-03 02:00 UTC
Had the following issue on my computer in both Ubuntu and Windows using Python 3.7.0.

```
C:\youtube-upload-master>python C:\youtube-upload-master\youtube-upload --title="Test" D:\OUT.mp4
Using client secrets: C:\Users\Mark\.client_secrets.json
Using credentials file: C:\Users\Mark\.youtube-upload-credentials.json
Traceback (most recent call last):
  File "C:\youtube-upload-master\youtube-upload", line 10, in <module>
    main.run()
  File "C:\youtube-upload-master\youtube_upload\main.py", line 257, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "C:\youtube-upload-master\youtube_upload\lib.py", line 42, in catch_exceptions
    fun(*args, **kwargs)
  File "C:\youtube-upload-master\youtube_upload\main.py", line 251, in main
    run_main(parser, options, args)
  File "C:\youtube-upload-master\youtube_upload\main.py", line 170, in run_main
    youtube = get_youtube_handler(options)
  File "C:\youtube-upload-master\youtube_upload\main.py", line 156, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "C:\youtube-upload-master\youtube_upload\auth\__init__.py", line 38, in get_resource
    storage = oauth2client.file.Storage(credentials_file)
AttributeError: module 'oauth2client' has no attribute 'file'
```

I have installed the script before on previous computers and never had any problem. To resolve this issue I put "from oauth2client import file" in main.py and I had no issue after that.

Not sure if this is related to the main setup with the client secrets and credential file. In the error I posted above it says it is using a credentials file but I know that file doesn't even exist yet because I didn't get the whole portion where the script asks you to follow the link and paste in the code. Once I added that import line in the main.py the script functioned like normal as shown below.

```
C:\youtube-upload-master>python C:\youtube-upload-master\youtube-upload --title="Test" D:\OUT.mp4
Using client secrets: C:\Users\Mark\.client_secrets.json
Using credentials file: C:\Users\Mark\.youtube-upload-credentials.json
C:\Users\Mark\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\_helpers.py:255: UserWarning: Cannot access C:\Users\Mark\.youtube-upload-credentials.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Check this link in your browser: https://accounts.google.com/o/oauth2/auth?client_id=529489928594-597ekj6pf1uni9n9lmjgft07ian76gvv.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.upload+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube&access_type=offline&response_type=code
Enter verification code: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Start upload: D:\OUT.mp4
```

The thing that I found strange is I never had this problem on two other computers I set this up on three months ago only till today when I installed python and attempted to set it up on this computer did I have this problem and couldn't figure out why.

**Comment by zhangolve** [comment] 2018-12-04 03:00
nearly same question.
Python 3.6.7

**Comment by feacluster** [comment] 2018-12-10 02:41
Thanks. I put "from oauth2client import file" in main.py and it worked like a charm!

**Comment by dawahnigeria** [comment] 2018-12-11 19:05
Exactly same issue
I put "from oauth2client import file" in main.py, but did not work
python 2.7.12

**Comment by jpcookie** [comment] 2018-12-12 22:50
Same problem now it's even after I know I have the oauth2client module installed

Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 9, in <module>
    from youtube_upload import main    
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 24, in <module>
    from oauth2client import file
ImportError: No module named oauth2client

sudo pip install oauth2client
Requirement already satisfied: oauth2client in /usr/local/lib/python3.7/dist-packages (4.1.3)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python3/dist-packages (from oauth2client) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from oauth2client) (4.0)
Requirement already satisfied: six>=1.6.1 in /usr/lib/python3/dist-packages (from oauth2client) (1.12.0)
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from oauth2client) (0.12.0)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/lib/python3/dist-packages (from oauth2client) (0.2.1)

sudo pip3 install oauth2client
Requirement already satisfied: oauth2client in /usr/local/lib/python3.7/dist-packages (4.1.3)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python3/dist-packages (from oauth2client) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from oauth2client) (4.0)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/lib/python3/dist-packages (from oauth2client) (0.2.1)
Requirement already satisfied: six>=1.6.1 in /usr/lib/python3/dist-packages (from oauth2client) (1.12.0)
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from oauth2client) (0.12.0)

**Comment by talha131** [comment] 2018-12-13 06:53
@feacluster Why don't you open a pull request with this change? Nonetheless, thanks a lot. Your comment saved me lots of time.

**Comment by yisraeldov** [comment] 2018-12-13 15:55
> Thanks. I put "from oauth2client import file" in main.py and it worked like a charm!

This worked for me as well.

**Comment by BookWorm0** [comment] 2018-12-31 23:59
Also, oauth2client is deprecated, according to https://pypi.org/project/oauth2client/.  They recommend we use google-auth and oauthlib instead.

**Comment by kootsoop** [comment] 2020-05-06 16:09
Closing as appears to be a duplicate of #245.

**Closed by kootsoop** 2020-05-06 16:09 UTC
