### ISSUE TITLE
could upload subtitles and videos together

### ISSUE THREAD

**Issue by yumupinglan** [tokland/youtube-upload#246] opened 2018-08-18 11:45 UTC
I need upload a standalone subtitles file with a video, how can I do that? Thanks in advance.

**Comment by BurhanDanger** [comment] 2018-09-01 05:57
https://github.com/tokland/youtube-upload/issues/171#issuecomment-397777185

**Comment by kootsoop** [comment] 2020-05-06 21:50
Duplicate of #171

**Closed by kootsoop** 2020-05-06 21:50 UTC
Labels: duplicate
