### ISSUE TITLE
Files bigger than 64 GB are refused?? Webupload accepts them!

### ISSUE THREAD

**Issue by De-M-oN** [tokland/youtube-upload#153] opened 2017-01-25 01:49 UTC
I have a F1 2016 race and I cant upload it.
```
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 808, in method
    raise MediaUploadSizeError("Media larger than: %s" % maxSize)
googleapiclient.errors.MediaUploadSizeError: Media larger than: 68719476736
```

The webuploader of youtube accepts such files !
Why not this program??

**Comment by Utty88** [comment] 2017-01-25 06:30
As the path points not to youtube-upload, but to the python version of googles API client, the issue is not inside youtube-upload.
The issue seems to be somehow in the API client youtube-upload uses. Maybe in line 808 of /usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py you can adjust the maximum upload size.

**Comment by NeoTheThird** [comment] 2017-02-22 14:32
Yes, looks like that file is causing the issue. A hack to fix it is replacing the lines 431 and 433 with `return int(9223372036854775807)`. I know, i know, it's a little esoteric. But if it works it ain't stupid. Processing takes forever though.

**Comment by NeoTheThird** [comment] 2017-02-22 14:47
I created an issue upstream: https://github.com/google/google-api-python-client/issues/354

**Comment by KenSharp** [comment] 2017-03-12 21:47
The limit is imposed by the API V2. API V3 increases this to 128 GB.

**Comment by tokland** [comment] 2017-05-16 17:30
Upstream problem, closing

**Closed by tokland** 2017-05-16 17:30 UTC

**Comment by aaronshaf** [comment] 2017-08-28 15:58
@NeoTheThird Thanks for the workaround. Works great.
