### ISSUE TITLE
The server encountered a temporary error and could not complete your request.

### ISSUE THREAD

**Issue by kataste** [tokland/youtube-upload#87] opened 2016-01-14 21:12 UTC
Hi, I have this error and wait change nothing, the problem is repeated at several attempt.

![error](https://cloud.githubusercontent.com/assets/6649027/12337720/e7d6c42e-bb0b-11e5-89d8-5f6e53d32583.PNG)

**Comment by tokland** [comment] 2016-01-14 21:23
It works here for me. No idea, I'll keep it open in case it happens to other people.

**Comment by kataste** [comment] 2016-01-23 13:09
I have a track concerning the solution. I reset my Oauth and reupload the json and it works for 2-3 video then the problem start again =o so i reset Oauth and it works for 2-3 video

**Comment by Djidiouf** [comment] 2016-01-24 15:32
I have the same problem.

**Comment by kataste** [comment] 2016-01-27 16:07
I have always this problem

**Comment by tokland** [comment] 2016-01-28 19:06
I see, it's happening to a lot of people. Can you anyone open an issue and report here? AFAIK, this is the place:

https://code.google.com/p/gdata-issues/issues/list?q=label:APi-YouTube

Thanks

**Comment by tudoanh** [comment] 2016-02-01 02:42
I've have that problem too. I've tried large file, and small file too, but I still had that problem.

**Comment by smmsadrnezh** [comment] 2016-02-16 20:54
I uploaded several videos successfully one month ago and nothing changed during this period but I have this problem now.
I changed youtube channel, tested different kinds of video titles and different video files, used a new and clean clone of this repository and reinstalling the script but still it's not working.
I guess the problem is during the upload process connection drops for a moment and it cannot retry and upload fails.

**Comment by josbrouwer** [comment] 2016-02-17 20:55
i've also got the same problem. I uploaded several videos successfully this week but the upload speed become very low and now i can't upload any more.
![screen shot 2016-02-17 at 21 51 35](https://cloud.githubusercontent.com/assets/17024591/13124521/2ccd7fda-d5c1-11e5-8116-32ecebcd7f04.png)

**Comment by tokland** [comment] 2016-02-17 21:03
Can we rule out that you reached some kind of quota?

**Comment by josbrouwer** [comment] 2016-02-17 21:14
Hi Arnau,

Yes because i've got this problem but sometimes a video file is uploaded.
But the last few days it was 8 out of 10 video's were this message.

As you see below, after i post the message on GitHub i've tried it 2 times and it worked, but now i get the same error again..

Regards Jos





[cid:1C125436-AD4A-4FB3-A4B1-ACC5210B9D9E]
Van: Arnau Sanchez <notifications@github.com<mailto:notifications@github.com>>
Beantwoorden - Aan: tokland/youtube-upload <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Wednesday 17 February 2016 22:03
Aan: tokland/youtube-upload <youtube-upload@noreply.github.com<mailto:youtube-upload@noreply.github.com>>
CC: Jos Brouwer <j.brouwer@lvbnetworks.nl<mailto:j.brouwer@lvbnetworks.nl>>
Onderwerp: Re: [youtube-upload] The server encountered a temporary error and could not complete your request. (#87)


Can we rule out that you reached some kind of quota?

-

**Comment by tokland** [comment] 2016-02-17 21:22
To check usage and quotas:

https://console.developers.google.com/apis/api/youtube/usage?project=youtube-python-upload&hl=ca&duration=PT1H

You are using your own ```client_secrets.json```, right?

**Comment by josbrouwer** [comment] 2016-02-17 21:24
Yes. I Will check it thanks!

Verzonden vanuit Outlook Mobile<https://aka.ms/qtex0l>




On Wed, Feb 17, 2016 at 1:22 PM -0800, "Arnau Sanchez" <notifications@github.com<mailto:notifications@github.com>> wrote:


To check usage and quotas:

https://console.developers.google.com/apis/api/youtube/usage?project=youtube-python-upload&hl=ca&duration=PT1H

You are using your own client_secrets.json, right?

-

**Comment by buchno** [comment] 2016-02-18 17:48
Can confirm getting very low speeds when uploading (~100kB/s), with it often ultimately failing after a while. The quota usage is 1600 per try, which is normal.

Using the [sample python script](https://developers.google.com/youtube/v3/guides/uploading_a_video) results in a much higher speed (~6000kB/s).

**Comment by josbrouwer** [comment] 2016-02-18 18:00
Same for me. Very low speed en failing.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Thu, Feb 18, 2016 at 9:48 AM -0800, "buchno" <notifications@github.com<mailto:notifications@github.com>> wrote:


Can confirm getting very low speeds when uploading (~100kB/s), with it often ultimately failing after a while. The quota usage is 1600 per try, which is normal.

Using the sample python script<https://developers.google.com/youtube/v3/guides/uploading_a_video> results in a much higher speed (~6000kB/s).

-

**Comment by tokland** [comment] 2016-02-18 18:43
The only difference I can see why the example script is the chunksize. Can you try?

```
    #upload_video.py
    media = apiclient.http.MediaFileUpload(path, chunksize=-1, resumable=True)
```

**Comment by buchno** [comment] 2016-02-18 23:30
Setting the chunksize to -1 fixed the upload speed, it now caps my connection.

**Comment by tokland** [comment] 2016-02-18 23:32
I guess the 502 keep appearing. The problem is that with -1 we have no progressbar. Can you try a value that still allows top speed?

**Comment by buchno** [comment] 2016-02-18 23:43
The smallest chunksize that caps my connection of 10MB/s seems to be about 4MB.

**Comment by tokland** [comment] 2016-02-19 08:52
[master 7def77cd] set chunksize to 4M

**Comment by Djidiouf** [comment] 2016-02-19 12:56
I just uploaded 2 videos without any retry needed and the progress bar never froze. Thank you

**Comment by josbrouwer** [comment] 2016-02-20 16:51
i'm uploading video's again! only the progress bar is not working anymore.

**Comment by tokland** [comment] 2016-02-22 09:01
@josbrouwer with a chunksize of 4M you won't see the progressbar for short videos. I assume that the 502 problem went away with this change, I'll close the issue. A chunksize of 4M makes the progresbar really clunky, ok.

**Closed by tokland** 2016-02-22 09:01 UTC

**Comment by josbrouwer** [comment] 2016-02-22 09:04
Oke thnaks, the 502 problem went away, I’m happy!;)


From: Arnau Sanchez
Reply-To: tokland/youtube-upload
Date: Monday 22 February 2016 10:01
To: tokland/youtube-upload
Cc: Jos Brouwer
Subject: Re: [youtube-upload] The server encountered a temporary error and could not complete your request. (#87)


@josbrouwer<https://github.com/josbrouwer> with a chunksize of 4M you won't see the progressbar for short videos. I assume that the 502 problem went away with this change, I'll close the issue. A chunksize of 4M makes the progresbar really clunky, ok.

**Comment by tokland** [comment] 2016-02-22 09:07
Great :) Finally the issue was indeed related to my script, sorry about that guys. If anyone is willing to invest the time, an issue regarding this parameters may be opened in their bug tracker: https://code.google.com/p/gdata-issues/issues/list?q=label:APi-YouTube

**Comment by BakermanLP** [comment] 2016-02-23 11:57
Just to report, the upload problems seem to be gone now after this patch. Thank you!
