### ISSUE TITLE
Could not upload the video

### ISSUE THREAD

**Issue by Jichao** [tokland/youtube-upload#69] opened 2015-10-23 23:22 UTC
Steps:
>jcyangzh@localhost ~]$ youtube-upload --title "kekekeke" tcp连接与半连接.mov --description="tcp" >--client-secrets=client_secrets.json
>Using client secrets: client_secrets.json
>Using credentials file: /home/jcyangzh/.youtube-upload-credentials.json
>Start upload: tcp连接与半连接.mov
>100% |###############################################| Time: 0:03:34   4.25 MB/s
>Video URL: https://www.youtube.com/watch?v=SNSV8CVi1No
>SNSV8CVi1No

But in the video manager of youtube, the video is `0% uploaded`, and the url `https://youtu.be/SNSV8CVi1No` does not work.

**Comment by tdragonite** [comment] 2015-11-06 10:52
Same problem here.

**Comment by tokland** [comment] 2015-11-06 12:49
Cannot reproduce. It happens always, with videos of any size?

**Comment by tdragonite** [comment] 2015-11-06 13:08
Happens sometimes, last time with video around 500 mb.

Tnx for ur answer :-)

**Comment by tokland** [comment] 2015-11-06 13:23
If you have some time, check what google has to say: https://goo.gl/DvvMIk :)

**Comment by Jichao** [comment] 2015-11-07 05:34
Happens every time for >1GB video.

**Comment by tokland** [comment] 2015-12-14 21:58
Since it seems to be a problem with Google API, I'll close the issue. Open it if you gather more info.

**Closed by tokland** 2015-12-14 21:58 UTC
